### PR TITLE
Serialize simulation status

### LINKED ISSUE #629: Handle loading results when serialize = false
If a simulation is executed with the flag serialize = false, the results can't be loaded 

```Julia
build_out = build!(sim; console_level = Logging.Warn, serialize = false)
execute_out = execute!(sim)
results = SimulationResults(sim)
```

error: 

```Julia
 Info: checking integrity of /Users/jdlara/cache/blue_texas/standard/14/data_store/simulation_store.h5
ERROR: LoadError: SystemError: opening file "system-6bbc5f77-da7d-4a7e-ba6e-8c6d4d430fd6.json": No such file or directory
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168
 [2] #systemerror#48 at ./error.jl:167 [inlined]
 [3] systemerror at ./error.jl:167 [inlined]
 [4] open(::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing) at ./iostream.jl:284
 [5] open at ./iostream.jl:273 [inlined]
 [6] open(::PowerSystems.var"#151#152", ::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:323
 [7] open at ./io.jl:323 [inlined]
 [8] deserialize(::Type{System}, ::String; time_series_read_only::Bool, time_series_directory::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:runchecks,),Tuple{Bool}}}) at /Users/jdlara/.julia/packages/PowerSystems/4kGrw/src/base.jl:1204
 [9] System(::String; kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:time_series_read_only,),Tuple{Bool}}}) at /Users/jdlara/.julia/packages/PowerSystems/4kGrw/src/base.jl:179
 [10] PowerSimulations.ProblemResults(::PowerSimulations.HdfSimulationStore, ::String, ::PowerSimulations.SimulationStoreProblemParams, ::PowerSimulations.SimulationStoreParams, ::String; load_system::Bool, results_output_path::Nothing) at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:51
 [11] (::PowerSimulations.var"#199#202"{Bool})(::PowerSimulations.HdfSimulationStore) at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:655
 [12] h5_store_open(::PowerSimulations.var"#199#202"{Bool}, ::String, ::String, ::String) at /Users/jdlara/.julia/dev/PowerSimulations/src/core/hdf_simulation_store.jl:117
 [13] h5_store_open at /Users/jdlara/.julia/dev/PowerSimulations/src/core/hdf_simulation_store.jl:114 [inlined]
 [14] SimulationResults(::String, ::Nothing; load_systems::Bool) at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:650
 [15] SimulationResults at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:625 [inlined] (repeats 2 times)
 [16] #SimulationResults#203 at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:673 [inlined]
 [17] SimulationResults(::Simulation) at /Users/jdlara/.julia/dev/PowerSimulations/src/core/simulation_results.jl:673
 [18] top-level scope at /Users/jdlara/cache/blue_texas/scripts/sims.jl:49
in expression starting at /Users/jdlara/cache/blue_texas/scripts/sims.jl:49
```

### PR DESCRIPTION
**Pull request by daniel-thom**
This allows blocking of reading results if the simulation failed.

Fixes #629

### CODE REVIEW

File: src/core/simulation.jl [hunk 1]
```diff
@@ -1381,3 +1384,30 @@ function deserialize_model(
         cd(orig)
     end
 end
+
+function serialize_status(sim::Simulation)
+    data = Dict("run_status" => string(get_simulation_status(sim)))
```
Comment (jd-lara) [inline src/core/simulation.jl:1389]: can't we just store a string the store attributes instead of adding an additional file to the output? seems strange to store a json with just the status.

File: src/core/simulation_results.jl [hunk 2]
```diff
@@ -639,6 +640,11 @@ function SimulationResults(path::AbstractString, execution = nothing; load_syste
         end
     end
 
+    status = deserialize_status(joinpath(execution_path, RESULTS_DIR))
+    if status != RunStatus.SUCCESSFUL
+        error("Results can only be read from a successful simulation: $status")
```
Comment (jd-lara) [inline src/core/simulation_results.jl:645]: we should just warn here or allow to override to recover some results before the fail
