### PR TITLE
fix bugs

### LINKED ISSUE #876: check for template coverage on system devices
add a check (and warning) if the template covers all active devices in a system

### LINKED ISSUE #878: MethodError: no method matching length(::PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus})
I'm trying to run the following:

```
results = SimulationResults(sim)
ac_results = get_decision_problem_results(results, "ACOPF")

slack_keys = [
    k for k in list_variable_keys(ac_results) if PSI.get_entry_type(k) ∈ [SystemBalanceSlackDown, SystemBalanceSlackUp]
]
slack_vars = Dict([k => read_realized_variables(ac_results, k) for k in slack_keys])
```

And I get this error:

```
LoadError: MethodError: no method matching length(::PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus})
Closest candidates are:
  length(!Matched::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(!Matched::Union{LinearAlgebra.Adjoint{T, <:Union{StaticArraysCore.StaticArray{Tuple{var"#s2"}, T, 1} where var"#s2", StaticArraysCore.StaticArray{Tuple{var"#s3", var"#s4"}, T, 2} where {var"#s3", var"#s4"}}}, LinearAlgebra.Diagonal{T, <:StaticArraysCore.StaticArray{Tuple{var"#s13"}, T, 1} where var"#s13"}, LinearAlgebra.Hermitian{T, <:StaticArraysCore.StaticArray{Tuple{var"#s10", var"#s11"}, T, 2} where {var"#s10", var"#s11"}}, LinearAlgebra.LowerTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s18", var"#s19"}, T, 2} where {var"#s18", var"#s19"}}, LinearAlgebra.Symmetric{T, <:StaticArraysCore.StaticArray{Tuple{var"#s7", var"#s8"}, T, 2} where {var"#s7", var"#s8"}}, LinearAlgebra.Transpose{T, <:Union{StaticArraysCore.StaticArray{Tuple{var"#s2"}, T, 1} where var"#s2", StaticArraysCore.StaticArray{Tuple{var"#s3", var"#s4"}, T, 2} where {var"#s3", var"#s4"}}}, LinearAlgebra.UnitLowerTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s24", var"#s25"}, T, 2} where {var"#s24", var"#s25"}}, LinearAlgebra.UnitUpperTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s21", var"#s22"}, T, 2} where {var"#s21", var"#s22"}}, LinearAlgebra.UpperTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s15", var"#s16"}, T, 2} where {var"#s15", var"#s16"}}, StaticArraysCore.StaticArray{Tuple{var"#s25"}, T, 1} where var"#s25", StaticArraysCore.StaticArray{Tuple{var"#s1", var"#s3"}, T, 2} where {var"#s1", var"#s3"}, StaticArraysCore.StaticArray{<:Tuple, T}} where T) at ~/.julia/packages/StaticArrays/68nRv/src/abstractarray.jl:1
  length(!Matched::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:172
  ...
Stacktrace:
  [1] length(g::Base.Generator{PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus}, PowerSimulations.var"#312#313"})
    @ Base ./generator.jl:50
  [2] _similar_shape(itr::Base.Generator{PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus}, PowerSimulations.var"#312#313"}, #unused#::Base.HasLength)
    @ Base ./array.jl:663
  [3] collect(itr::Base.Generator{PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus}, PowerSimulations.var"#312#313"})
    @ Base ./array.jl:786
  [4] read_realized_variables(res::PowerSimulations.SimulationProblemResults{PowerSimulations.DecisionModelSimulationResults}, variables::PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ PowerSimulations ~/.julia/packages/PowerSimulations/HKwUO/src/simulation/simulation_problem_results.jl:268
  [5] read_realized_variables(res::PowerSimulations.SimulationProblemResults{PowerSimulations.DecisionModelSimulationResults}, variables::PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus})
    @ PowerSimulations ~/.julia/packages/PowerSimulations/HKwUO/src/simulation/simulation_problem_results.jl:267
  [6] (::Main.__FRANKLIN_1802956.var"#11#12")(k::PowerSimulations.VariableKey{PowerSimulations.SystemBalanceSlackDown, PowerSystems.Bus})
    @ Main.__FRANKLIN_1802956 ./none:0
  [7] iterate
    @ ./generator.jl:47 [inlined]
  [8] collect(itr::Base.Generator{Vector{PowerSimulations.VariableKey{T, PowerSystems.Bus} where T<:PowerSimulations.VariableType}, Main.__FRANKLIN_1802956.var"#11#12"})
    @ Base ./array.jl:787

```

### PR DESCRIPTION
**Pull request by jd-lara**
closes #876 
closes #878 

Requires https://github.com/NREL-SIIP/PowerSystems.jl/pull/913

### CODE REVIEW

File: src/operation/operation_model_interface.jl [hunk 1]
```diff
@@ -211,7 +211,24 @@ end
...
+    modeled_types = get_component_types(template)
+    system = get_system(model)
+    system_component_types = PSY.get_existing_component_types(system)
+    for m in setdiff(modeled_types, system_component_types)
+        @warn "The template doesn't include models for components of type $(m), consider changing the template" _group =
+            LOG_GROUP_MODELS_VALIDATION
+    end
+    for m in setdiff(system_component_types, modeled_types)
+        @warn "The system data doesn't include components of type $(m), consider changing the models in the template" _group =
+            LOG_GROUP_MODELS_VALIDATION _group = LOG_GROUP_MODELS_VALIDATION
```
Comment (daniel-thom) [inline src/operation/operation_model_interface.jl:225]: double setting of `_group`

Comment (daniel-thom) [reply src/operation/operation_model_interface.jl:225]: Approve after the minor fix

**Comment by claytonpbarrows** [comment]
I'm late, but this looks good. Thanks!
