### PR TITLE
Empty contributing devices case

### LINKED ISSUE #493: Simulation fails when services' contributing devices is empty
If a system in the model has empty contributing devices, the simulation fails.

### PR DESCRIPTION
**Pull request by jd-lara**
closes #493

### CODE REVIEW

File: src/services_models/services_constructor.jl [hunk 1]
```diff
@@ -30,8 +30,12 @@ function construct_service!(
 ) where {SR <: PSY.Reserve}
     services_mapping = PSY.get_contributing_device_mapping(sys)
     time_steps = model_time_steps(psi_container)
-    names = (PSY.get_name(s) for s in services)
-
+    names = [
```
Comment (daniel-thom) [inline src/services_models/services_constructor.jl:33]: I understand why these changes fix the problem.  However, this is a non-trivial amount of logic that I suspect other users will have to replicate and possibly forget or mess up when they make similar functions.  Is that true?  If so, would it be better to filter out these services in the place where this function is called?

Comment (jd-lara) [reply src/services_models/services_constructor.jl:33]: That's why I suggested to not create the entry in the output of `PSY.get_contributing_device_mapping`

File: src/services_models/services_constructor.jl [hunk 2]
```diff
@@ -23,15 +23,14 @@ end
...
+    services::Vector{SR},
     sys::PSY.System,
     model::ServiceModel{SR, RangeReserve},
     devices_template::Dict{Symbol, DeviceModel},
 ) where {SR <: PSY.Reserve}
     services_mapping = PSY.get_contributing_device_mapping(sys)
     time_steps = model_time_steps(psi_container)
-    names = (PSY.get_name(s) for s in services)
-
+    names = [PSY.get_name(s) for s in services]
```
Comment (daniel-thom) [inline src/services_models/services_constructor.jl:33]: @jd-lara Does the content of `names` need to be consistent with the services you add variables and constraints for?  You are calling add_param_container and add_cons_container with names that could later be skipped.

Comment (jd-lara) [reply src/services_models/services_constructor.jl:33]: No, the validate services already made those checks and only adds the services that are valid.

File: src/services_models/services_constructor.jl [hunk 3]
```diff
@@ -62,15 +61,15 @@ function construct_service!(
...
-            )].contributing_devices
+            services_mapping[(type = SR, name = PSY.get_name(service))].contributing_devices
         if !isempty(incompatible_device_types)
             contributing_devices =
                 [d for d in contributing_devices if typeof(d) ∉ incompatible_device_types]
         end
-
+        if isempty(contributing_devices)
+            @warn("The contributing devices for service $(PSY.get_name(service)) is empty, cinsider removing the service from the system")
+            continue
```
Comment (daniel-thom) [inline src/services_models/services_constructor.jl:71]: This service name was added above in the `names` variable.  I was asking if this inconsistency is a problem.  The validate function did not check this condition.

Also: s/cinsider/consider/

File: src/services_models/services_constructor.jl [hunk 4]
```diff
@@ -7,8 +7,8 @@ function construct_services!(
     isempty(services_template) && return
     for service_model in values(services_template)
         @debug "Building $(service_model.service_type) with $(service_model.formulation) formulation"
-        services = PSY.get_components(service_model.service_type, sys)
-        if validate_available_services(service_model.service_type, services)
+        services = service_model.service_type[]
+        if validate_available_services(service_model.service_type, services, sys)
```
Comment (daniel-thom) [inline src/services_models/services_constructor.jl:11]: Consider renaming this to `validate_available_services!` so that it's more obvious that you're mutating `services`.
